# Generated by Django 3.2.7 on 2021-10-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageformat',
            old_name='new_message',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='messageformat',
            old_name='user_referred',
            new_name='y',
        ),
    ]
